### ISSUE TITLE
Sponsored Feature: Add Cardano Compatibility to BIP39 Mnemonic and Passphrase Recovery (For Shelly Era Addresses/Accounts)

### ISSUE THREAD

**Issue by 3rdIteration** [3rdIteration/btcrecover#222]
**Tasks**
- [x] Add ability to reverse pubkeyhash from bech32 Cardano Base addresses
- [x] Add functionality related to Ed25519 address derivation
- [x] Add Ledger Address Derivation (See: https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/Ledger.md)
- [x] Add Icarus Address Derivation (See: https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/CIP-0003.md)
- [x] Integrate standalone code in to seedrecover.py
- [x] Extend support to btcrecover.py
- [x] Add special case to handle Trezor for 24 word seeds derivation (See: https://github.com/trezor/trezor-firmware/pull/1388)
- [x] Add documentation
- [x] Add Unit Tests
- [x] Enable GPU Acceleration (seed recovery)
- [x] Enable GPU Acceleration (passphrase recovery)

**External Repo ToDo: (Generally issues found in other repos as part of this implementation)** (beyond the scope of this issue)
- [ ] Create PR to fix two mistakes in CIP003 Ledger derivation psuedocode + fix incorrect test vector for key derivation with repeats. 
- [x] Create separate repo for python cardano address derivation (libs used in BTCRecover, created for this project)

**Future Work** (beyond the scope of this issue)

- Switch out pure python ed25519 libraries for something much faster (Eg pynacl) as this is currently a major bottleneck, especially for GPU accelerated processing. (Still fast enough to be useful, but much slower that existing BIP 39, even after considering the slower initial derivation that cardano uses)
- Look at bugfix to OpenCL brute so it can correctly handle the entropy lengths which require padding for 96 bit dklen( that the Trezor-24word scenario creates, as opposed to 32 bytes, or 15 or 21 word icarus seeds) Until a much faster ed25519 library is implemented, there is no point addressing this... Seems to be a bug where the first 64bits are correct but the last 32 (so the second block) is incorrect. (Only an issue with dklen > 64 and when the entropy requires padding)

Background docco & Reference Implementations
https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/CIP-0003.md
https://cardano-python.readthedocs.io/en/latest/wallet.html
https://github.com/LedgerHQ/orakolo/blob/master/src/python/orakolo/HDEd25519.py
https://docs.rs/ed25519-bip32/0.4.0/ed25519_bip32/
https://github.com/trezor/trezor-firmware/tree/master/core/src/apps/cardano
https://github.com/LedgerHQ/app-cardano
https://github.com/superdarkbit/nano-bip32-ed25519/tree/master/python_equivalents
https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Primitive/AddressDerivation/Icarus.hs
https://github.com/input-output-hk/cardano-addresses
https://github.com/sdlck/cardano-utils/blob/master/address-generator/addrGenerator.py
https://github.com/pyca/pynacl

**Comment by lunarpool** [comment]
Looking forward! 👍 

Dusan - lunarpool

**Comment by 3rdIteration** [comment]
External Repo ToDo:

- [ ] Create PR to fix typo in CIP003 Ledger derivation psuedocode. (cc hmac message should uses data, not seed)

**Comment by 3rdIteration** [comment]
Initial working code for seedrecover.py pushed to Cardano-Shelly Branch as of https://github.com/3rdIteration/btcrecover/commit/c2bf7a3e022f4317451808c817627b75870963c8

Still needs a bit of work in terms of full functionality, passphrase recovery and GPU acceleration, but it's working well for Yoroi/Adalite/Ledger/Trezor/Deadalus type seeds this first part represente the bulk of the work. (So well on track to get it all sorted and merged with master within a fortnight)

**Comment by 3rdIteration** [comment]
@lunarpool this has been merged in to master. The GPU acceleration is there on the hashing side, but won't get much real benefit until a faster ed25519 implimentation is swapped in. (These aren't yet readily available and mature for Cardano in the same way they are for things like Bitcoin, but that will likely change in the next few months as there are a few projects underway for this)

**Comment by endlessbux** [comment]
> That's exactly what I was hoping for. I have already written [a simple script](https://github.com/hashcat/hashcat/files/7402195/run.py.txt) for that (see [hashcat issue](https://github.com/hashcat/hashcat/issues/3013)). It can be used as a reference for the spending password recovery feature.

Hi there, I was trying to run your script but I get this: `ImportError: cannot import name 'BLAKE2b' from 'Crypto.Hash'`

What are the pip requirements for that script?

**Comment by quangthienit1994** [comment]
@not-mms @3rdIteration  Hi All, It's supported or not ? Because my issue like @not-mms

**Comment by 3rdIteration** [comment]
Shelly is supported, Byron is not.

**Comment by quangthienit1994** [comment]
![image](https://user-images.githubusercontent.com/22471650/148486500-6619933c-3dd9-415b-b8d8-deea01573e7d.png)
@3rdIteration , thank for response, I see there lines has been commented ? the reason is scrypt can't run on GPU ?

**Comment by 3rdIteration** [comment]
It can, it just depends on the parameters (some work and some don't)

**Comment by quangthienit1994** [comment]
@3rdIteration Thank for your response, Do you know why test can't passed ?
![image](https://user-images.githubusercontent.com/22471650/148495293-10eab62b-12ab-4718-8bae-76746203afe5.png)

**Comment by Dragovioon** [comment]
Hi. I was thinking you can help me. I have Lost both the spending password and the seed phrase for the deadalus Wallet. I have vêem looking for help for years now. I still have the old deadalus folder where I Open the account with the secret.key file and all. Can you help me?

**Comment by 3rdIteration** [comment]
Deadalus wallet recovery isn't supported at this time and would be a separate issue if you wanted to sponsor it.

**Comment by Dragovioon** [comment]
> Deadalus wallet recovery isn't supported at this time and would be a separate issue if you wanted to sponsor it.

I know but what a need is a way to use the data folders I have to find the spending password. As I already uses the recovery option to recovery my Wallet. But I still need the spending password

**Comment by 3rdIteration** [comment]
Please don't spam this issue, it is not related to Deadalus... If you want to sponsor an additional feature to recover the spending password then that would go in a new issue. (And you can email me at steve@cryptoguide.tips to organize that)

**Comment by Dragovioon** [comment]
Hi I lost both the spending password and the seed, I stilo have the Byron wallet Open and the secret Key file. Is there any way to recover my funds?

**Comment by 3rdIteration** [comment]
Deadalus wallet file password recovery is currently not supported, but it could likely be added if you wanted to sponsor it.
